// Transaction Protocol
syntax = "proto3";

import "common.proto";

enum TransactionType {
    DEPOSIT = 0;
    WITHDRAW = 1;
}

message Money {
    uint64 units = 1;
    uint32 nanos = 2;
}

message NewTransactionRequest {
    TransactionType type = 1;
    Money amount = 2;
    string account = 3;
}

message NewTransactionResponse {
    common.Status status = 1;
    string transaction_id = 2;
}

service TransactionProto {
    rpc NewTransaction(NewTransactionRequest) returns (NewTransactionResponse) {}
}
